name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Job to build and test the client-side code
  build-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        # Set the default working directory for all run steps in this job
        working-directory: ./client
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # The cache will now look for package-lock.json inside the working-directory
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  # Job to build and test the server-side code
  build-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        # Set the default working directory for all run steps in this job
        working-directory: ./server
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # The cache will now look for package-lock.json inside the working-directory
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
